### ISSUE TITLE
renderQueqe for the shader

### ISSUE THREAD

**Issue by grapefruitlips** [sinnwrig/URP-Volumetric-Lighting#2]
Hello! How can I set renderQueqe to Transparent+10 for the shader? 
Because when the camera inside the fog we can see the water (3000 renderQueqe), for example
Water is rendering "before" the fog, even if it far away
I changed "beforeTransparents" to true in VolumetricFogFeature.cs but nothing changed

**Comment by sinnwrig** [comment]
There has been a setting added to the Render Feature that allows you to select if you want to render before or after the transparent objects pass. If you set the option to _not_ draw before transparents, it might properly occlude your water shader, although it won't interact properly with the fog and will be completely covered. Only materials with a render queue 2500 or less actually draw to the camera depth texture, so the fog volume can't determine whether or not it is marching in front or behind transparent objects.

There are also a ton of people who have encountered the same problem, and I found a forum post that implemented a possible solution using the Render Objects feature. If you'd like to give it a try and see if it helps, here is the link: [Transparent Shader Problem](https://forum.unity.com/threads/transparent-shader-problem.1059206/)

This is part of a more general problem with transparents and the depth texture/buffer due to the way they work. There are solutions, such as rendering a second pass with _only_ occluder objects drawing directly to the depth texture. I will look into implementing this in the future using a custom layer mask for transparent occluders instead of delegating the work to Render Objects.
