### ISSUE TITLE
Opacity control?

### ISSUE THREAD

**Issue by XJonOneX** [sinnwrig/URP-Volumetric-Lighting#3]
Let me just say, this asset is fantastic!

Is there any way to make the fog more opaque the further away you are from it? Currently it's the opposite, it gets more opaque the closer you are to it. I'm trying to hide object and terrain pop-in at a distance with this.

**Comment by XJonOneX** [comment]
After tweaking some of the Lighting and Noise settings, I was able to achieve the look I wanted.

**Comment by sinnwrig** [comment]
Hi Jon, I'm glad to hear you got the results you wanted, and I apologize for not responding a tad bit earlier. For the record, I designed this asset to target scenarios where you need localized volumes of fog, as I believed that for the goal you described (occluding larger, distant objects) the fog found in the scene lighting settings would work. Because of this most of the default settings try to blend out the fog the further you get away to try smoothly culling the fog earlier as ray-marching can quickly chew away at performance. 

If you would like to add a feature request for fog to fade out at further distances, I may be able to get around to it sometime, but it would not be high on my priority list. However, if you are in need of a solution quickly, I would point you to [this part](https://github.com/sinnwrig/URP-Fog-Volumes/blob/main/Shaders/Include/VolumetricFog.hlsl#L146) of VolumetricFog.hlsl, where you might be able to get your desired result by swapping some shader variables around.
