### ISSUE TITLE
Are there any plans to support Unity 6 and the Render Graph API

### ISSUE THREAD

**Issue by burningthumb** [sinnwrig/URP-Volumetric-Lighting#5]
This is just a question. I was wondering if you plan to update this to support Unity 6 (2023 a.k.a. 6000) and the Render Graph API?

**Comment by sinnwrig** [comment]
At the moment, I don't plan on updating this repository further as I am moving away from unity and began working on [other projects](https://github.com/ProwlEngine/Prowl). However, from what I can understand, this asset should support later URP versions (if they don't change the API a gazillion times), and doesn't rely on any features which the render graph would particularly speed up.

If this asset breaks on newer Unity/URP versions, I'm more than glad to add patches and bugfixes, and accept PR's that do the same or add features. However, I'm not inclined to put in Render Graph support, due to the negligible speedup it would provide for the way this asset works (it wouldn't optimize the always-required textures), and the drop of backwards-compatibility on older Unity versions.
